### ISSUE TITLE
Documentation Storybook Add-On

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#144]
We'd like to get a documentation add-on for Storybook. [This is a potential option](https://www.npmjs.com/package/@storybook/addon-docs), but part of this ticket is researching one that works well.

[Here](https://github.com/NYPL/nypl-design-system/wiki/Tester-for-Component-Documentation) is some sample documentation for the Button component.

## Tasks
- [ ] Add documentation add-on
- [ ] Connect one story to instance of Airtable documentation
- [ ] Remove "Show Info" button

**Comment by helenvholmes** [comment]
An additional thought I had is that the UX team keeps its documentation in Airtable. We might best be served by an Airtable Storybook add-on if such a thing exists.

**Comment by helenvholmes** [comment]
Closing via #369.
