### ISSUE TITLE
What is the Design System named?

### ISSUE THREAD

**Issue by scooooooooby** [NYPL/nypl-design-system#7]
[Google Form results](https://docs.google.com/forms/d/1sb0rpROrCICnjEod7VY-6T-icKxXcm49e4PMpZmO95U/edit#responses)

## To-Dos
- [ ] Figure out next steps. Another Google Survey? Discussion with the UX team?
- [ ] Flesh out requirements that name much fulfill
  - [ ] Name must be available as an npm package
  - [ ] Name must be meaningful in the library context
  - [ ] Name must satisfy UX team
- [ ] Update npm package names
  - [ ] Prefix npm package names with `@nypl/`

**Comment by helenvholmes** [comment]
I'm going to close this out. It looks like we're going forward with `nypl-ds` and that's fine.
